2020-07-27 12:11:42,550 INFO: Microblog startup [in C:\Users\Rakshith\PycharmProjects\saas\app\__init__.py:51]
2020-07-27 12:12:20,829 INFO: Microblog startup [in C:\Users\Rakshith\PycharmProjects\saas\app\__init__.py:51]
2020-07-27 12:12:29,847 INFO: Microblog startup [in C:\Users\Rakshith\PycharmProjects\saas\app\__init__.py:51]
2020-07-27 12:56:24,240 INFO: Microblog startup [in C:\Users\Rakshith\PycharmProjects\saas\app\__init__.py:51]
2020-07-27 18:36:45,115 INFO: Microblog startup [in C:\Users\Rakshith\PycharmProjects\saas\app\__init__.py:71]
2020-07-27 18:36:51,615 ERROR: Exception on /login [GET] [in C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Rakshith\PycharmProjects\saas\app\auth\routes.py", line 29, in login
    return render_template('login.html', form=form, title='Sign In')
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2020-07-27 18:37:54,075 ERROR: Exception on /login [GET] [in C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Rakshith\PycharmProjects\saas\app\auth\routes.py", line 29, in login
    return render_template('login.html', form=form, title='Sign In')
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\Rakshith\PycharmProjects\saas\app\templates\base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\Rakshith\anaconda3\envs\flaskcourse\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
